# this is the root URL for your site - keep empty if testing locally (or set --baseurl '' in jekyll serve) but if you plan on using
# jekyll on github pages make sure to specify your baseurl to match the repo directory name
baseurl: /Wiki

# site runs locally at localhost:4000 when you run `jekyll serve --watch`
port: 4001

# ensure UTF-8 character encoding. Be sure to add <meta charset="utf-8"> as well!
encoding: utf-8

plugins:
 - jekyll-sitemap
 - jekyll-avatar

# repository: technet2/Wiki

exclude:
 - .vs